# belvo_client.model.transactions_complete_request500_response.TransactionsCompleteRequest500Response

This error occurs when we (Belvo) have encountered an internal system error (sorry about that) or due to an unsupported response from the institution.   

## Model Type Info
Input Type | Accessed Type | Description | Notes
------------ | ------------- | ------------- | -------------
list, tuple,  | tuple,  | This error occurs when we (Belvo) have encountered an internal system error (sorry about that) or due to an unsupported response from the institution.    | 

### Tuple Items
Class Name | Input Type | Accessed Type | Description | Notes
------------- | ------------- | ------------- | ------------- | -------------
[**UnexpectedError**](UnexpectedError.md) | [**UnexpectedError**](UnexpectedError.md) | [**UnexpectedError**](UnexpectedError.md) |  | 

[[Back to Model list]](../../README.md#documentation-for-models) [[Back to API list]](../../README.md#documentation-for-api-endpoints) [[Back to README]](../../README.md)

